# Generated by Django 2.0.4 on 2018-04-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='Id')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('site', models.CharField(max_length=255, verbose_name='Sitio')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefono')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('long', models.FloatField(verbose_name='Longitud')),
            ],
            options={
                'ordering': ('id', 'rating'),
            },
        ),
    ]
