# Generated by Django 2.0.4 on 2018-04-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
